-- Generated by scripts/build-seed.mjs from seed/xu-holdings-sce-12mo.csv
-- taxes_usd and fees_usd split out of the old other-charges bucket.
-- other_charges_usd is the residual: energy + demand + taxes + fees + other = total_new_charges.
ALTER TABLE bills ADD COLUMN taxes_usd TEXT NOT NULL DEFAULT '';
ALTER TABLE bills ADD COLUMN fees_usd TEXT NOT NULL DEFAULT '';
ALTER TABLE bills ADD COLUMN line_items_json TEXT NOT NULL DEFAULT '[]';

UPDATE bills SET
  taxes_usd = '',
  fees_usd = '',
  other_charges_usd = '466.48',
  line_items_json = '[]'
WHERE source_key = 'xu-holdings-irwindale|259000-081267|2025-08-28|2025-09-28';

UPDATE bills SET
  taxes_usd = '',
  fees_usd = '',
  other_charges_usd = '404.13',
  line_items_json = '[]'
WHERE source_key = 'xu-holdings-irwindale|259000-081267|2025-09-29|2025-10-27';

UPDATE bills SET
  taxes_usd = '',
  fees_usd = '',
  other_charges_usd = '429.11',
  line_items_json = '[]'
WHERE source_key = 'xu-holdings-irwindale|259000-081267|2025-10-28|2025-11-28';

UPDATE bills SET
  taxes_usd = '',
  fees_usd = '',
  other_charges_usd = '419.74',
  line_items_json = '[]'
WHERE source_key = 'xu-holdings-irwindale|259000-081267|2025-11-29|2025-12-29';

UPDATE bills SET
  taxes_usd = '',
  fees_usd = '',
  other_charges_usd = '437.37',
  line_items_json = '[]'
WHERE source_key = 'xu-holdings-irwindale|259000-081267|2025-12-30|2026-01-28';

UPDATE bills SET
  taxes_usd = '',
  fees_usd = '',
  other_charges_usd = '442.94',
  line_items_json = '[]'
WHERE source_key = 'xu-holdings-irwindale|259000-081267|2026-01-29|2026-03-01';

UPDATE bills SET
  taxes_usd = '',
  fees_usd = '',
  other_charges_usd = '428.59',
  line_items_json = '[]'
WHERE source_key = 'xu-holdings-irwindale|259000-081267|2026-03-02|2026-03-30';

UPDATE bills SET
  taxes_usd = '',
  fees_usd = '',
  other_charges_usd = '420.19',
  line_items_json = '[]'
WHERE source_key = 'xu-holdings-irwindale|259000-081267|2026-03-31|2026-04-29';

UPDATE bills SET
  taxes_usd = '',
  fees_usd = '',
  other_charges_usd = '425.45',
  line_items_json = '[]'
WHERE source_key = 'xu-holdings-irwindale|259000-081267|2026-04-30|2026-05-31';

UPDATE bills SET
  taxes_usd = '',
  fees_usd = '',
  other_charges_usd = '539.80',
  line_items_json = '[]'
WHERE source_key = 'xu-holdings-irwindale|259000-081267|2026-06-01|2026-06-29';

UPDATE bills SET
  taxes_usd = '',
  fees_usd = '',
  other_charges_usd = '537.07',
  line_items_json = '[]'
WHERE source_key = 'xu-holdings-irwindale|259000-081267|2026-06-30|2026-07-29';

UPDATE bills SET
  taxes_usd = '203.12',
  fees_usd = '323.66',
  other_charges_usd = '0.00',
  line_items_json = '[{"label":"Facilities rel demand","amount_usd":"364.09","category":"demand"},{"label":"On peak","amount_usd":"550.10","category":"energy"},{"label":"Mid peak","amount_usd":"27.46","category":"energy"},{"label":"Off peak","amount_usd":"611.36","category":"energy"},{"label":"Wildfire fund charge","amount_usd":"30.39","category":"fee"},{"label":"Customer charge","amount_usd":"268.43","category":"fee"},{"label":"On peak","amount_usd":"129.95","category":"demand"},{"label":"On peak","amount_usd":"420.97","category":"energy"},{"label":"Mid peak","amount_usd":"10.19","category":"energy"},{"label":"Off peak","amount_usd":"249.95","category":"energy"},{"label":"Fixed recovery charge","amount_usd":"24.84","category":"fee"},{"label":"Irwindale UUT","amount_usd":"201.58","category":"tax"},{"label":"State tax","amount_usd":"1.54","category":"tax"}]'
WHERE source_key = 'xu-holdings-irwindale|259000-081267|2026-07-30|2026-08-27';

