import { readFileSync, writeFileSync } from "node:fs";

const columns = [
  "utility",
  "customer_name",
  "customer_account",
  "service_account",
  "meter_id",
  "pod_id",
  "service_address",
  "service_city",
  "service_state",
  "service_zip",
  "rate_schedule",
  "rin",
  "billing_period_start",
  "billing_period_end",
  "billing_days",
  "kwh_total",
  "kwh_on_peak",
  "kwh_mid_peak",
  "kwh_off_peak",
  "kwh_super_off_peak",
  "demand_kw_max",
  "demand_kw_on_peak",
  "demand_kw_mid_peak",
  "demand_kw_off_peak",
  "demand_kw_super_off_peak",
  "energy_charges_usd",
  "demand_charges_usd",
  "taxes_usd",
  "fees_usd",
  "other_charges_usd",
  "total_new_charges_usd",
  "amount_due_usd",
  "due_date",
  "bill_prepared_date",
  "service_voltage",
  "source_file",
  "parser_id",
  "parse_confidence",
  "notes",
  "line_items_json",
];

const chargeColumns = ["taxes_usd", "fees_usd", "line_items_json"];
const legacyColumns = columns.filter((column) => !chargeColumns.includes(column));

const siteId = "xu-holdings-irwindale";
const createdAt = "2026-09-21T00:00:00.000Z";
const rows = parseCsv(readFileSync(new URL("../seed/xu-holdings-sce-12mo.csv", import.meta.url), "utf8"));
if (rows.length !== 12) throw new Error(`expected 12 seed rows, got ${rows.length}`);
const header = Object.keys(rows[0]);
if (header.join() !== columns.join()) throw new Error("CSV header does not match bill columns");

const first = rows[0];
const meterId = `${siteId}:${first.meter_id}`;
const sql = [];
sql.push("-- Generated by scripts/build-seed.mjs from seed/xu-holdings-sce-12mo.csv");
sql.push("INSERT INTO sites (id, name, created_at) VALUES");
sql.push(`  ('${siteId}', 'XU Holdings — Irwindale', '${createdAt}')`);
sql.push("ON CONFLICT(id) DO UPDATE SET name = excluded.name;");
sql.push("");
sql.push("INSERT INTO meters (");
sql.push("  id, site_id, meter_id, utility, customer_name, customer_account, service_account, pod_id,");
sql.push("  service_address, service_city, service_state, service_zip, created_at");
sql.push(") VALUES (");
sql.push(
  `  '${meterId}', '${siteId}', ${q(first.meter_id)}, ${q(first.utility)}, ${q(first.customer_name)}, ${q(first.customer_account)}, ${q(first.service_account)}, ${q(first.pod_id)},`,
);
sql.push(
  `  ${q(first.service_address)}, ${q(first.service_city)}, ${q(first.service_state)}, ${q(first.service_zip)}, '${createdAt}'`,
);
sql.push(") ON CONFLICT(site_id, meter_id) DO UPDATE SET");
sql.push("  utility = excluded.utility,");
sql.push("  customer_name = excluded.customer_name,");
sql.push("  service_address = excluded.service_address;");
sql.push("");

for (const row of rows) {
  const sourceKey = `${siteId}|${row.meter_id}|${row.billing_period_start}|${row.billing_period_end}`;
  const id = `seed-${row.source_file.replace(/[^A-Za-z0-9._-]+/g, "_")}`;
  const insertColumns = [
    "id",
    "site_id",
    "r2_key",
    "created_at",
    "updated_at",
    "status",
    "source_key",
    "text_excerpt",
    ...legacyColumns,
  ];
  const values = [
    q(id),
    q(siteId),
    "NULL",
    q(createdAt),
    q(createdAt),
    q("ok"),
    q(sourceKey),
    q(""),
    ...legacyColumns.map((column) => q(row[column] ?? "")),
  ];
  sql.push(`INSERT INTO bills (${insertColumns.join(", ")})`);
  sql.push(`VALUES (${values.join(", ")})`);
  sql.push("ON CONFLICT(source_key) DO UPDATE SET");
  sql.push(`  status = excluded.status,`);
  sql.push(legacyColumns.map((column) => `  ${column} = excluded.${column}`).join(",\n") + ";");
  sql.push("");
}

writeFileSync(new URL("../migrations/0002_seed_xu_holdings.sql", import.meta.url), `${sql.join("\n")}\n`);
console.log(`wrote migrations/0002_seed_xu_holdings.sql (${rows.length} bills)`);

const chargeSql = [];
chargeSql.push("-- Generated by scripts/build-seed.mjs from seed/xu-holdings-sce-12mo.csv");
chargeSql.push("-- taxes_usd and fees_usd split out of the old other-charges bucket.");
chargeSql.push("-- other_charges_usd is the residual: energy + demand + taxes + fees + other = total_new_charges.");
chargeSql.push("ALTER TABLE bills ADD COLUMN taxes_usd TEXT NOT NULL DEFAULT '';");
chargeSql.push("ALTER TABLE bills ADD COLUMN fees_usd TEXT NOT NULL DEFAULT '';");
chargeSql.push("ALTER TABLE bills ADD COLUMN line_items_json TEXT NOT NULL DEFAULT '[]';");
chargeSql.push("");
for (const row of rows) {
  const sourceKey = `${siteId}|${row.meter_id}|${row.billing_period_start}|${row.billing_period_end}`;
  chargeSql.push("UPDATE bills SET");
  chargeSql.push(`  taxes_usd = ${q(row.taxes_usd ?? "")},`);
  chargeSql.push(`  fees_usd = ${q(row.fees_usd ?? "")},`);
  chargeSql.push(`  other_charges_usd = ${q(row.other_charges_usd ?? "")},`);
  chargeSql.push(`  line_items_json = ${q(row.line_items_json ?? "[]")}`);
  chargeSql.push(`WHERE source_key = ${q(sourceKey)};`);
  chargeSql.push("");
}
writeFileSync(new URL("../migrations/0004_charge_components.sql", import.meta.url), `${chargeSql.join("\n")}\n`);
console.log(`wrote migrations/0004_charge_components.sql (${rows.length} bills)`);

function q(value) {
  return `'${String(value).replaceAll("'", "''")}'`;
}

function parseCsv(text) {
  const table = [];
  let row = [];
  let cell = "";
  let inQuotes = false;
  for (let index = 0; index < text.length; index += 1) {
    const char = text[index];
    if (inQuotes) {
      if (char === '"') {
        if (text[index + 1] === '"') {
          cell += '"';
          index += 1;
        } else inQuotes = false;
      } else cell += char;
      continue;
    }
    if (char === '"') inQuotes = true;
    else if (char === ",") {
      row.push(cell);
      cell = "";
    } else if (char === "\n") {
      row.push(cell);
      table.push(row);
      row = [];
      cell = "";
    } else if (char !== "\r") cell += char;
  }
  if (cell || row.length) {
    row.push(cell);
    table.push(row);
  }
  const header = table[0];
  return table.slice(1).filter((cells) => cells.some((value) => value !== "")).map((cells) => {
    const record = {};
    header.forEach((column, index) => {
      record[column] = cells[index] ?? "";
    });
    return record;
  });
}
